//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JointAdmissionModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JointAdmissionModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _100中區五專免試國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_100中區五專免試國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100中投區國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_100中投區國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100五專免試國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_100五專免試國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100北區五專免試國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_100北區五專免試國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_中投一般 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_中投一般", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_中投特種 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_中投特種", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_五專一般 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_五專一般", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_五專特種 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_五專特種", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_台南一般 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_台南一般", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_台南特種 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_台南特種", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_竹苗一般 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_竹苗一般", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100學年度國中在校成績證明單_竹苗特種 {
            get {
                object obj = ResourceManager.GetObject("_100學年度國中在校成績證明單_竹苗特種", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100新竹高中免試國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_100新竹高中免試國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _100高雄高中多元入學匯入檔 {
            get {
                object obj = ResourceManager.GetObject("_100高雄高中多元入學匯入檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _101台南區嘉義區高中免試國中報名系統檔 {
            get {
                object obj = ResourceManager.GetObject("_101台南區嘉義區高中免試國中報名系統檔", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _102新竹高中免試三學期各科成績 {
            get {
                object obj = ResourceManager.GetObject("_102新竹高中免試三學期各科成績", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _102新竹高中免試在校學習成績資料 {
            get {
                object obj = ResourceManager.GetObject("_102新竹高中免試在校學習成績資料", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
